[tools]
node = "latest"
deno = "latest"
bun = "latest"
pnpm = "latest"
go = "latest"
uv = "latest"
java = "latest"
rust = "latest"
prek = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python", "node"]
status.missing_tools = "never"
experimental = true
